server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
  instance:
    instance-id: jurisdiction-0  #此实例注册到Eureka服务端的唯一实例ID
    prefer-ip-address: true
spring:
  application:
    name: jurisdiction      #此实例注册到Eureka服务端的name